language: node_js
node_js: stable
addons:
  apt:
    update: true
cache:
  directories:
  - node_modules
install:
- git clone https://github.com/theme-next/hexo-theme-next themes/next
- npm install
script:
- hexo g
after_success:
- cd ./public
- git init
- git config user.name "wuchengqi"
- git config user.email "wuchengqi577@gmail.com"
- git add .
- git commit -m "Update site"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - dev
env:
  global:
  - GH_REF: github.com/chengqiwu/cz.github.io.git
  - secure: 4apZx3q7o9BGzlrBWQ05lKSy/6EhWbvu6AgeSnBydhRcE9TtLdg2U9RB1g263SoPVojQatJ0mOTTD/R9ahJZVgyOxrcxij8Uvq96Lm855hHD+xy3nn2RvJvngbQGaycLeV+HI8bykSLR8tC5xEWtgQszGMBCRV2jNsxK4+8iahChvAFfQlHRxYXDtucwmmvj3p2FNvNGJL2Ra5gM+8IPwoALw9CAnG+HXmCgMM8RZ+4IKWVmI5yRRDY18yZGdHNNJYzA1XLyf3HlOIhLQCWoDbljCu24ZX1QdBdvJ0ahx8sePWgeq1Nm6bM5KgH29eI6Ymdyly0XXw/2XZ9evS3Rg5vOdfRokzLbBdJnbCA54c99pGrK7A0JNB880LtcpGCp38PRHd1/shLz0WE93nNfd5DC7j7QZUA6/0+HOUJje1TvQLAFtit8uIvYFMbPlyJS3HJpc/KJRnOJ79q+rxL9UtRdVwBGWM+zz+AN4HkLmglSHxKMGUh6WsmGQxSJlC68ToynTZX17INC+W0PIZgEK3NT7OsyWop03xnlV9mwjUvKfqGjO7LMrnrT/TDbZ8qiCqNFrJdpNzOFWflEA2OKPt4AfUAftQ99CTGrrSEUWRabewjOxIKzB28jWEPDNKJi/4S/Mgo7LbmF+L5KpiHX1d7k3a3GupAkPwQ7UC8MR2A=
dd:
  secure: pZXVEUP70nFe4u4mr3AG+JngqF+FGRNdn4z5FtfrgSfWsIupzs5AgDrPRD08vM63VPhNUawx78f6zygFIe/jBXjAHMX/lTu6MhkwwVxugk1nAQN2/3CSLd3GK1pwuBgsN3hkKR5TLTUfQNG6FDJvK0Mtcjnm5U0GHAQdhsDPooL3i2bG44nbNk7Q/Fe+6vkvbGSbB8BwghKa7H1a3exNY6zHcV2RrT25J4mDwXSeUtFB9zno3kldfJxu8fyfMcXCM/1zhZiC/pm8Q+31NbSIEZp35jG1bp4bUNGKAZrSLaYpWXSyhlAmyOQkSkAujaJ2Qd6jRVbZmBFTGqC7V0iwoj0GgNt5LZQnqIJWUMI/C5KzEQm0cZln1kP/dnxhDQiDIFJN5Zpamee9D5vWmE0VpQ0YVYG/vJqNg9GJBS6HyaVdnljE9ir36baTq4QPJo+tF+eaJsnWU54HCesEj4eGwiKIlELbl8xeh6IhFlLtxXPvVISRxuxfa2il4EROrgzDmHEK0Wxp5KOQPFDJTnuP+aYeKQ1cm2I8FDpodIoKsgabQ6VInXLiLrNQzmJfJjq1lDSa8lL5mlqexIU8/CkQi3iymYQBFgI2T8WctYAR+5Uh7k+bIochh6l3Mi4HikczQJ10GOhGfzKHRU62Ks0BDpzaAXGyP6hTR2zhlEOvO/8=
