language: node_js
node_js: stable
addons:
  apt:
    update: true
cache:
  directories:
  - node_modules
install:
- npm install
script:
- hexo g
after_success:
- cd ./public
- git init
- git config user.name "wuchengqi"
- git config user.email "wuchengqi577@gmail.com"
- git add .
- git commit -m "Update site"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - dev
env:
  global:
  - GH_REF: github.com/chengqiwu/cz.github.io.git
  - secure: 4apZx3q7o9BGzlrBWQ05lKSy/6EhWbvu6AgeSnBydhRcE9TtLdg2U9RB1g263SoPVojQatJ0mOTTD/R9ahJZVgyOxrcxij8Uvq96Lm855hHD+xy3nn2RvJvngbQGaycLeV+HI8bykSLR8tC5xEWtgQszGMBCRV2jNsxK4+8iahChvAFfQlHRxYXDtucwmmvj3p2FNvNGJL2Ra5gM+8IPwoALw9CAnG+HXmCgMM8RZ+4IKWVmI5yRRDY18yZGdHNNJYzA1XLyf3HlOIhLQCWoDbljCu24ZX1QdBdvJ0ahx8sePWgeq1Nm6bM5KgH29eI6Ymdyly0XXw/2XZ9evS3Rg5vOdfRokzLbBdJnbCA54c99pGrK7A0JNB880LtcpGCp38PRHd1/shLz0WE93nNfd5DC7j7QZUA6/0+HOUJje1TvQLAFtit8uIvYFMbPlyJS3HJpc/KJRnOJ79q+rxL9UtRdVwBGWM+zz+AN4HkLmglSHxKMGUh6WsmGQxSJlC68ToynTZX17INC+W0PIZgEK3NT7OsyWop03xnlV9mwjUvKfqGjO7LMrnrT/TDbZ8qiCqNFrJdpNzOFWflEA2OKPt4AfUAftQ99CTGrrSEUWRabewjOxIKzB28jWEPDNKJi/4S/Mgo7LbmF+L5KpiHX1d7k3a3GupAkPwQ7UC8MR2A=
